name: KitPvP
main: io.github.aphex124.Main_KitPvP
version: 1.0.1-SNAPSHOT
description: A plugin that allows server owners to have the popular Minecraft server minigame, Kit PvP, on their server.
author: Aphex124
website: https://www.apwolfpack.com/