name: KitPvP
version: 0.1 - SNAPSHOT
main: io.github.aphex124.Main_KitPvP
description: A full KitPvP Plugin!
commands:
   basic:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>